const dummyData = [
  { id: 1, name: "Apo" },
  { id: 2, name: "Asokoro" },
  { id: 3, name: "Bwari" },
  { id: 4, name: "Central Business District" },
  { id: 5, name: "Chika" },
  { id: 6, name: "Dakibiya" },
  { id: 7, name: "Dakwo" },
  { id: 8, name: "Dei-Dei" },
  { id: 9, name: "Duboyi" },
  { id: 10, name: "Durumi" },
  { id: 11, name: "Dutse" },
  { id: 12, name: "Gaduwa" },
  { id: 13, name: "Galadimawa" },
  { id: 14, name: "Garki" },
  { id: 15, name: "Gudu" },
  { id: 16, name: "Guzape" },
  { id: 17, name: "Gwagwa" },
  { id: 18, name: "Gwagwalada" },
  { id: 19, name: "Gwarinpa" },
  { id: 20, name: "Idu" },
  { id: 21, name: "Jabi" },
  { id: 22, name: "Jahi" },
  { id: 23, name: "Jikwoyi" },
  { id: 24, name: "Kabusa" },
  { id: 25, name: "Kado" },
  { id: 26, name: "Kajini" },
  { id: 27, name: "Karsana" },
  { id: 28, name: "Karu" },
  { id: 29, name: "Katampe" },
  { id: 30, name: "Kaura" },
  { id: 31, name: "Keffi" },
  { id: 32, name: "Kubwa" },
  { id: 33, name: "Kuchigworo" },
  { id: 34, name: "Kukwaba District" },
  { id: 35, name: "Lokogoma" },
  { id: 36, name: "Lugbe" },
  { id: 37, name: "Mabushi" },
  { id: 38, name: "Maitama" },
  { id: 39, name: "Mbora" },
  { id: 40, name: "Mpape" },
  { id: 41, name: "Nyanya" },
  { id: 42, name: "Pyakasa" },
  { id: 43, name: "Utako" },
  { id: 44, name: "Waru-Pouma" },
  { id: 45, name: "Wumba" },
  { id: 46, name: "Wuse" },
  { id: 47, name: "Wuye" },
  { id: 48, name: "Zuba" },
];

export { dummyData };
