const data = {
  properties: {
    propertyId: [
      "13012894",
      "13073105",
      "13948573",
      "13275981",
      "13095642",
      "13785429",
      "13425736",
      "13246857",
    ],
  },
  section: [
    {
      id: 1,
      name: "Details",
      fieldData: [
        {
          id: 1,
          parentKey: "1",
          inputName: "cadestralZone",
          placeholder: "Cadestral Zone",
          inputType: "select",
          options: [
            { id: 1, name: "Abaji" },
            { id: 2, name: "Abuja Municipal Area Council (AMAC)" },
            { id: 3, name: "Bwari" },
            { id: 4, name: "Gwagwalada" },
            { id: 5, name: "Kuje" },
            { id: 6, name: "Kwali" },
          ],
          required: true,
        },
        {
          id: 2,
          parentKey: "1",
          inputName: "assetNumber",
          placeholder: "Asset Number",
          inputType: "text",
          required: false,
        },
        {
          id: 3,
          parentKey: "1",
          inputName: "streetName",
          placeholder: "Street Name",
          inputType: "text",
          required: false,
        },
        {
          id: 4,
          parentKey: "1",
          inputName: "propertyAddress",
          placeholder: "Property Address",
          inputType: "text",
          required: false,
        },
        {
          id: 5,
          parentKey: "1",
          inputName: "ratingDistrict",
          placeholder: "Rating District",
          inputType: "select",
          options: [
            { id: 1, name: "Rating One" },
            { id: 2, name: "Rating Two" },
            { id: 3, name: "Rating Three" },
          ],
          required: false,
        },
        {
          id: 6,
          parentKey: "1",
          inputName: "category",
          placeholder: "Category",
          inputType: "select",
          options: [
            { id: 1, name: "Category One" },
            { id: 2, name: "Category Two" },
            { id: 3, name: "Category Three" },
          ],
          required: false,
        },
        {
          id: 7,
          parentKey: "1",
          inputName: "propertyType",
          placeholder: "Property Type",
          inputType: "select",
          options: [
            { id: 1, name: "Property Type One" },
            { id: 2, name: "Property Type Two" },
            { id: 3, name: "Property Type Three" },
          ],
          required: false,
        },
        {
          id: 8,
          parentKey: "1",
          inputName: "group",
          placeholder: "Group",
          inputType: "select",
          options: [
            { id: 1, name: "Group One" },
            { id: 2, name: "Group Two" },
            { id: 3, name: "Group Three" },
          ],
          required: false,
        },
        {
          id: 9,
          parentKey: "1",
          inputName: "propertyUse",
          placeholder: "Property Use",
          inputType: "select",
          options: [
            { id: 1, name: "Property Use One" },
            { id: 2, name: "Property Use Two" },
            { id: 3, name: "Property Use Three" },
          ],
          required: false,
        },
        {
          id: 10,
          parentKey: "1",
          inputName: "occupationStatus",
          placeholder: "Occupation Status",
          inputType: "select",
          options: [
            { id: 1, name: "Occupation Status One" },
            { id: 2, name: "Occupation Status Two" },
            { id: 3, name: "Occupation Status Three" },
          ],
          required: false,
        },
      ],
    },
    {
      id: 2,
      name: "Valuation",
      fieldData: [
        {
          id: 1,
          parentKey: "2",
          inputName: "annualValue",
          placeholder: "Annual Value",
          inputType: "text",
          required: true,
        },
        {
          id: 2,
          parentKey: "2",
          inputName: "ratePayable",
          placeholder: "Rate Payable",
          inputType: "text",
          required: false,
        },
        {
          id: 3,
          parentKey: "2",
          inputName: "arrears",
          placeholder: "Arrears",
          inputType: "text",
          required: false,
        },
        {
          id: 4,
          parentKey: "2",
          inputName: "penalty",
          placeholder: "Penalty",
          inputType: "text",
          required: false,
        },
        {
          id: 5,
          parentKey: "2",
          inputName: "grandTotal",
          placeholder: "Grand Total",
          inputType: "text",
          required: false,
        },
      ],
    },
    {
      id: 3,
      name: "Occupant Details",
      fieldData: [
        {
          id: 1,
          parentKey: "3",
          inputName: "occupantsFirstName",
          placeholder: "Occupants First Name",
          inputType: "text",
          required: false,
        },
        {
          id: 2,
          parentKey: "3",
          inputName: "occupantsLastName",
          placeholder: "Occupants Last Name",
          inputType: "text",
          required: false,
        },
        {
          id: 3,
          parentKey: "3",
          inputName: "occupantsPhoneNumber",
          placeholder: "Occupants Phone Number",
          inputType: "text",
          required: false,
        },
        {
          id: 4,
          parentKey: "3",
          inputName: "occupantsEmail",
          placeholder: "Occupants Email",
          inputType: "text",
          required: true,
        },
        {
          id: 5,
          parentKey: "3",
          inputName: "occupantsMaritalStatus",
          placeholder: "Occupants Marital Status",
          inputType: "text",
          required: true,
        },
      ],
    },
  ],
};

export { data };
